name: Dev Branch Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'
    branches:
      - dev

jobs:
  canaryBuild:
    name: Canary Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[s]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Gradle Build
        run: |
          sudo bash <<EOF
          [ -d "$HOME/.gradle" ] && mv $HOME/.gradle /root
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./gradlew assembleFullRelease
          mv /root/.gradle $HOME
          chgrp -R $UID $HOME/.gradle
          chown -R $UID $HOME/.gradle
          EOF
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk -name "*arm64-v8a*.apk")
          echo ::set-env name=APK_FILE_ARMV7::$(find TMessagesProj/build/outputs/apk -name "*armeabi*.apk")
          echo ::set-env name=APK_FILE_X86::$(find TMessagesProj/build/outputs/apk -name "*x86-*.apk")
          echo ::set-env name=APK_FILE_X64::$(find TMessagesProj/build/outputs/apk -name "*x86_64*.apk")
      - name: Upload Canary Apk
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CANARY_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.APK_FILE }}
      - name: Upload Canary Apk ( armv7 )
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CANARY_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.APK_FILE_ARMV7 }}
      - name: Upload Canary Apk ( x86 )
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CANARY_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.APK_FILE_X86 }}
      - name: Upload Canary Apk ( x64 )
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CANARY_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ env.APK_FILE_X64 }}